### ISSUE TITLE
Link 

### ISSUE THREAD

**Issue by AngieKay** [learn-co-curriculum/dsc-conditional-probability#2]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

https://learning.flatironschool.com/courses/4244/pages/conditional-probability

## What should be changed?

Conditional probability, Independence and Bayes rule link goes to a professor bio. Is there a specific paper of his that is recommended?

**Comment by hoffm386** [comment]
The link has been updated (and an additional backup link provided). Thanks for flagging!
